### ISSUE TITLE
File key.properties

### ISSUE THREAD

**Issue by ColquePaxi** [MSzalek-Mobile/weight_tracker#22]
Hi man! Great use case.

Say me how to get / generate key.properties file? I'm newbie on Firebase.

Can you help me?  

Error:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Projetos\weight_tracker\android\app\build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':app'.
> C:\Projetos\weight_tracker\android\key.properties (O sistema não pode encontrar o arquivo especificado)

```

**Comment by MarcinusX** [comment]
Hi! :)
`key.properties` file is a file that stores aliases and passwords, so that it won't be in main repository.
It should look like this:
```
storePassword=XXX
keyPassword=XXX
keyAlias=XXX
storeFile=../key.jks
```
You can create it by your own, but if you don't need to sign your application, best course would be to remove signingConfigs from gradle [here](https://github.com/MSzalek-Mobile/weight_tracker/blob/master/android/app/build.gradle#L40-L47) and [here](https://github.com/MSzalek-Mobile/weight_tracker/blob/master/android/app/build.gradle#L50).
Tell me how it goes :)
